[project]
name = "pytorch-gym"
version = "0.1.0"
description = "RL projects with gymnasium"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gymnasium>=1.2.0",
    "numpy>=2.3.2",
    "pygame>=2.6.1",
    "tensorboard>=2.20.0",
    "torch>=2.7.1",
]
